name: 'Install Drupal 8+ instance'
description: 'Install dependencies on a Drupal 8+ project'
inputs:
  dev:
    description: 'Prod or development release (composer --dev)'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: "Compute SHA"
      id: sha
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      shell: bash

    - name: "Validate composer schema"
      run: composer validate --no-ansi --strict
      shell: bash

    - name: "Install prod dependencies"
      if: ${{ inputs.dev == 'false' }}
      run: composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader
      shell: bash

    - name: "Install dev dependencies"
      if: ${{ inputs.dev == 'true' }}
      run: composer install --no-ansi --no-interaction --no-progress
      shell: bash
